require:
  - rubocop-sequel

AllCops:
  TargetRubyVersion: 2.5

Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['dataset_module', 'describe', 'helpers']

Metrics/AbcSize:
  Max: 20.45

Metrics/MethodLength:
  Max: 13
