dist: trusty
sudo: false

language: ruby
rvm:
  - 2.5

addons:
  postgresql: 10
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

services:
  - docker

before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1
  - psql -c 'create database frankfurter_test;' -U postgres

bundler_args: --without development
env:
  global:
    - APP_ENV=test
    - PGPORT=5433

deploy:
  provider: script
  script: bash bin/docker_push
  on:
    branch: master
